# OSX/Linux (https://github.com/travis-ci-tester/toolchain-table)

# Workaround for https://github.com/travis-ci/travis-ci/issues/8363
language:
  - minimal

# Container-based infrastructure (Linux)
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-can-I-use-container-based-infrastructure%3F
sudo:
  - false

# Install packages differs for container-based infrastructure
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-do-I-install-APT-sources-and-packages%3F
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - python3-pip

      - g++-5
      - gcc-5
      - g++-7
      - gcc-7

dist:
  - trusty

matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      env: TOOLCHAIN=osx-10-9 CONFIG=Release

install:
  # Info about OS
  - uname -a

  - export HOMEBREW_NO_AUTO_UPDATE=1

  - export CTEST_OUTPUT_ON_FAILURE=1

  # Install Python 3
  - if [[ "`uname`" == "Darwin" ]]; then travis_retry brew install python3; fi

  # Install Python package 'requests'
  # 'easy_install3' is not installed by 'brew install python3' on OS X 10.9 Maverick
  - if [[ "`uname`" == "Darwin" ]]; then pip3 install requests; fi
  - if [[ "`uname`" == "Linux" ]]; then travis_retry pip3 install --user requests; fi
  # fix broken clang link on Travis-CI
  - if [[ "`uname`" == "Linux" ]]; then  mkdir clang-bin; ln -s /usr/local/clang-5.0.0/bin/clang++ clang-bin/clang++-5.0; fi
  - if [[ "`uname`" == "Darwin" ]]; then mkdir clang-bin; ln -s /usr/bin/clang++ clang-bin/clang++-5.0; fi
  # Download polly
  - wget --quiet https://github.com/ruslo/polly/archive/master.zip
  - unzip -q master.zip
  # Install dependencies (CMake, Android NDK)
  - POLLY_SOURCE_DIR="`pwd`/polly-master"
  - python3 "${POLLY_SOURCE_DIR}/bin/install-ci-dependencies.py"

  # Tune locations
  - export PATH="`pwd`/_ci/cmake/bin:`pwd`/clang-bin:${PATH}"
  # Installed if toolchain is Android (otherwise directory doesn't exist)
  - export ANDROID_NDK_r10e="`pwd`/_ci/android-ndk-r10e"
  - export ANDROID_NDK_r11c="`pwd`/_ci/android-ndk-r11c"
  - export ANDROID_NDK_r15c="`pwd`/_ci/android-ndk-r15c"
  - export ANDROID_NDK_r17="`pwd`/_ci/android-ndk-r17"

script:
  - >
    python3 "${POLLY_SOURCE_DIR}/bin/build.py"
    --toolchain ${TOOLCHAIN}
    --config ${CONFIG}
    --ios-multiarch
    --ios-combined
    --install
    --clear
    --test
    --tail 200

cache:
  directories:
  - $HOME/.hunter
